//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Guardian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleDetail
    {
        public int Id { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Form { get; set; }
        public System.DateTime DateOfRelease { get; set; }
        public Nullable<bool> IsLiked { get; set; }
        public string ArticleUrl { get; set; }
        public string ImageUrl { get; set; }
    }
}
