//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Guardian.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Child_GuardianEntities : DbContext
    {
        public Child_GuardianEntities()
            : base("name=Child_GuardianEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleDetail> ArticleDetails { get; set; }
        public virtual DbSet<QuestionDetail> QuestionDetails { get; set; }
        public virtual DbSet<MedicineDetail> MedicineDetails { get; set; }
    }
}
