//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Guardian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetail
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public Nullable<System.TimeSpan> TimeToTake { get; set; }
        public Nullable<int> DosesPerWeek { get; set; }
        public string Note { get; set; }
        public Nullable<int> Reminder { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<int> IntervalHours { get; set; }
    }
}
