//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Child_Guardian.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionDetail
    {
        public int Id { get; set; }
        public string QuestionContent { get; set; }
        public string Answer { get; set; }
        public int ParentId { get; set; }
        public int ChildId { get; set; }
        public Nullable<int> DoctorId { get; set; }
    }
}
